package io.fasthome.fenestram_messenger.profile_guest_impl.presentation.profile_guest

import io.fasthome.fenestram_messenger.presentation.base.ui.BottomSheetFragment
import io.fasthome.fenestram_messenger.profile_guest_impl.presentation.profile_guest.ProfileGuestFragment

class ProfileGuestBottomFragment : BottomSheetFragment(ProfileGuestFragment::class)